# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45913e9c634c394c019b91cbab2a0819fbb702dd61a98cc545d35fe25d84e7b35de82801faa95381d90b886c2f903fd4efb404e618d1ccf32dcff73a5ecfc948

test:
  secret_key_base: fae549bb3085ec8dccafd83c26a035c81d8cd05092411517b91e26a878307e3506a98a24bd4b333c98208bd25dcb5bae588f0a88cb33e97db64fcf3d95759b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
